apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tendril.fullname" . }}-config
type: Opaque
stringData:
  cluster_id: {{ .Values.config.clusterId | quote }}
  api_token: {{ .Values.config.apiToken | quote }}
  supabase_url: {{ .Values.config.supabaseUrl | quote }}
  supabase_key: {{ .Values.config.supabaseKey | quote }}
  grape_api_origin: {{ .Values.config.grapeApiOrigin | quote }}
