{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tendril.serviceAccountName" . }}
  annotations:
    {{- if .Values.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.roleArn }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
